# Generated by Django 4.2.5 on 2023-09-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'exchanges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrismaMigrations',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=64)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('migration_name', models.CharField(max_length=255)),
                ('logs', models.TextField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('applied_steps_count', models.IntegerField()),
            ],
            options={
                'db_table': '_prisma_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('token', models.OneToOneField(db_column='token', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arb_spotter_app.tokens')),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('exchange', models.TextField()),
                ('percentage_change', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('b_a_spread', models.FloatField(blank=True, null=True)),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'market_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OneDayOhlcvData',
            fields=[
                ('token', models.OneToOneField(db_column='token', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arb_spotter_app.tokens')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('exchange', models.TextField()),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'one_day_ohlcv_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OneHourOhlcvData',
            fields=[
                ('token', models.OneToOneField(db_column='token', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arb_spotter_app.tokens')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('exchange', models.TextField()),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'one_hour_ohlcv_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OneMinOhlcvData',
            fields=[
                ('token', models.OneToOneField(db_column='token', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='arb_spotter_app.tokens')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('exchange', models.TextField()),
                ('updatedat', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'one_min_ohlcv_data',
                'managed': False,
            },
        ),
    ]
